version: "3.8"

networks:
  default:
    external:
      name: stc_nw
    
services: 
  transparencia:
    image: thielserra/ubuntu2204-apache-php71
    tty: true
    container_name: ${PWD%/*/*}_container
    entrypoint: sh /docker-entrypoint.sh 
    restart: "always"
    volumes:
      - "../:/var/www/html"
      # - "./php/php.ini:/etc/php.ini"
      # - "./apache/apache2.conf:/etc/apache2/apache2.conf"
      - "./apache/sites-available:/etc/apache2/sites-available"
      - "./apache/logs:/var/log/apache2"
    ports:
      - "8060:80"
    networks:
      - default
